#https://www.docker.com/blog/containerized-python-development-part-1/
FROM python:3.8 AS builder

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir --user -r requirements.txt

FROM python:3.8-slim

RUN apt-get update && apt-get upgrade -y && apt-get install -y wkhtmltopdf xvfb

WORKDIR /usr/src/app

# copy only the dependencies installation from the 1st stage image
COPY --from=builder /root/.local /root/.local

COPY . .

CMD [ "python", "-u", "toot.py" ]
