version: '3.3'

services:
  generator-microservices-mastodon-bot:
    build:
      context: ./ # Local
      dockerfile: Dockerfile_arm64
    container_name: generator-microservices-mastodon-bot
    hostname: generator-microservices-mastodon-bot
#        ports:
#        - "80:80"
    restart: unless-stopped
    env_file:
      - environment.env
    secrets:
      - cert-chain.pem

secrets:                        # top level secrets block
  cert-chain.pem:
    file: cert-chain.pem
